Shared Basis Rotate test
ComputationalCryoEM/ASPIRE-Python pull request #1057
Opened 2023-11-28 15:17 UTC by garrettwrong

Replacing two specific (FFB, FLE) basis rotate tests with a simpler (and faster) shared test for all the 2d steerables.

Initially I put them in `test_rotation.py`, migrating that towards pytest.  Changed mind, preferred, `test_rotation.py` to target the `Rotation` class and put the rotate tests in a new file `test_steerable_bases_2d.py`

2023-11-30 13:27 UTC, j-c-c requested changes
Looks good. Just the one suggestion.

2023-11-30 13:27 UTC, j-c-c commented on tests/test_steerable_bases_2d.py
> +            rot_radians * 180 / np.pi, resample=PILImage.BILINEAR
Looks like `BICUBIC` gets the `atol` down to .15-ish for the expensive tests.

2023-11-30 13:42 UTC, garrettwrong commented on tests/test_steerable_bases_2d.py
> +            rot_radians * 180 / np.pi, resample=PILImage.BILINEAR
Yeah, that's right, after the normalizing commit things got a little better. Changed.

2023-11-30 14:05 UTC, j-c-c approved these changes
LGTM!

2023-12-07 12:04 UTC, garrettwrong commented
Merging.  Centralizes and expands unit test coverage to additional 2D basis. Converts some older tests towards pytest fixtures. No new features.

2023-12-07 12:04 UTC, merged