ClassAvgSource SymmetryGroup Pass-through
ComputationalCryoEM/ASPIRE-Python pull request #1151
Opened 2024-07-08 17:40 UTC by j-c-c

Looks like we were missing the `symmetry_group` pass-through for `ClassAvgSource`'s. Added the pass-through with a test to merge into #1149, so we're actually taking advantage of boosting in the C4 experimental reconstruction.

2024-07-10 12:32 UTC, garrettwrong requested changes
Wouldn't you need to do the same for all subclasses of `ImageSource` then?...

2024-07-10 17:41 UTC, j-c-c commented
> Wouldn't you need to do the same for all subclasses of `ImageSource` then?...

The other subclasses already handle `symmetry_group` pass-through and all were being tested aside from `IndexedSource`, for which I've just added a test.

2024-07-11 12:41 UTC, garrettwrong commented
Okay great, looks like it was passing through via `_rlnSymmetryGroup` metadata.

2024-07-11 12:42 UTC, garrettwrong approved these changes

2024-07-11 12:58 UTC, janden approved these changes
:+1:

2024-07-11 13:03 UTC, merged