Batch class avg
ComputationalCryoEM/ASPIRE-Python pull request #1216
Opened 2024-12-18 14:11 UTC by garrettwrong

Stashing WIP before vacation.  Still needs a lot of cleanup and testing.

2025-01-03 19:02 UTC, garrettwrong commented
Passing along for initial review.  I believe #1214 should go in first, then this will need to be rebased, maybe resolving some conflicts along the way.

2025-01-13 14:09 UTC, j-c-c submitted a review, later dismissed
Looks good!

2025-01-15 20:41 UTC, janden requested changes
Looks great! Just two things.

2025-01-15 20:41 UTC, janden commented on src/aspire/classification/averager2d.py
> +                # (cnt, n_transl) * (cnt, 1) -> (cnt, n_transl)
`(cnt, n_rot) * (cnt, 1) -> (cnt, n_rot)`?

2025-01-15 20:41 UTC, janden commented on src/aspire/classification/averager2d.py
> +                #      would currently be superflous.
I think that makes sense, but let's rename it `dot_products` so that there's no confusion.

2025-01-16 13:35 UTC, garrettwrong commented on src/aspire/classification/averager2d.py
> +                # (cnt, n_transl) * (cnt, 1) -> (cnt, n_transl)
Sure :), changed.

2025-01-16 13:35 UTC, garrettwrong commented on src/aspire/classification/averager2d.py
> +                #      would currently be superflous.
Okay. I changed this code and the corresponding attribute from `correlations` ~> `dot_product`. This crept into some of the docs and a unit test, but was all string replacements in a single commit. No functional changes.

2025-01-16 13:37 UTC, garrettwrong commented
I want to discuss/confirm the class hierarchy during our meeting and if no changes come out of that I'll merge this then.

2025-01-16 15:57 UTC, garrettwrong commented
Factored the base image rotation table outside the shift loop like we discussed in the meeting.

2025-01-16 19:45 UTC, janden commented
> Factored the base image rotation table outside the shift loop like we discussed in the meeting.

Cool. Any speedup?

2025-01-16 21:27 UTC, garrettwrong commented
> > Factored the base image rotation table outside the shift loop like we discussed in the meeting.
> 
> Cool. Any speedup?

Yes. Using GPU mode for 179px and 50 nbrs this saves about 0.3s per class (44.5 vs 44.8 s).  I'll call it 1%.  I think relative to the matmuls the vector vector broadcast multiplication is very fast for the GPU.  On the host, much larger improvement, more like 10%.

Either way across 3-100k classes I'll definitely take it :). Thanks.

2025-01-17 13:24 UTC, merged