add preprocess example using experimental dataset
ComputationalCryoEM/ASPIRE-Python pull request #302
Opened 2020-10-20 21:23 UTC by junchaoxia

Partially address issue #299.

2020-10-22 12:23 UTC, janden requested changes

2020-10-22 12:23 UTC, janden commented on tutorials/examples/preprocess_imgs_exp
> +"""
Change extension to `.py.dontrun`.

2020-10-22 12:23 UTC, janden commented on tutorials/examples/preprocess_imgs_exp
> +starfile_in = '/tigress/junchaox/CryoEMdata/empiar10028/shiny_2sets.star'
Capital letters for the variable name.

2020-10-22 12:23 UTC, janden commented on tutorials/examples/preprocess_imgs_exp
> +logger.info('This script illustrates how to preprocess experimental CryoEM images')
Just print statements.

2020-10-22 12:23 UTC, janden commented on tutorials/examples/preprocess_imgs_exp
> +if max_resolution < source.L:
No need for if statement.

2020-10-22 15:00 UTC, junchaoxia commented on tutorials/examples/preprocess_imgs_exp
> +"""
Done.

2020-10-22 15:00 UTC, junchaoxia commented on tutorials/examples/preprocess_imgs_exp
> +starfile_in = '/tigress/junchaox/CryoEMdata/empiar10028/shiny_2sets.star'
Done.

2020-10-22 15:00 UTC, junchaoxia commented on tutorials/examples/preprocess_imgs_exp
> +if max_resolution < source.L:
Done.

2020-10-22 15:00 UTC, junchaoxia commented on tutorials/examples/preprocess_imgs_exp
> +logger.info('This script illustrates how to preprocess experimental CryoEM images')
Done.

2020-10-23 20:20 UTC, vineetbansal commented on tutorials/examples/preprocess_imgs_exp.py.dontrun
> +#!/usr/bin/env  python3.6
#!/usr/bin/env  python

2020-10-23 20:21 UTC, vineetbansal commented on tutorials/examples/preprocess_imgs_exp.py.dontrun
> +data_folder = '/path/to/untarred/empiar/dataset/'
I guess make this capitalized as well.

2020-10-26 14:28 UTC, junchaoxia commented on tutorials/examples/preprocess_imgs_exp.py.dontrun
> +#!/usr/bin/env  python3.6
Done.

2020-10-26 14:28 UTC, junchaoxia commented on tutorials/examples/preprocess_imgs_exp.py.dontrun
> +data_folder = '/path/to/untarred/empiar/dataset/'
Done in new commit f0db5cd.

2020-10-29 12:50 UTC, janden approved these changes

2020-10-29 13:58 UTC, merged