Update readme
ComputationalCryoEM/ASPIRE-Python pull request #335
Opened 2020-11-16 17:18 UTC by garrettwrong

Looking over readme in preparation for our RC. Very minor updates.  I'll probably just keep this around as a draft in case I see any odds and ends in the next two weeks. 

This intentionally ignores the CLI stuff (quickstart) because I am looking at that as a separate topic for now.

2020-11-25 12:27 UTC, garrettwrong commented
This remains minor readme updates, mainly rephrasing the posture on pip installs.

2020-12-03 12:26 UTC, janden requested changes

2020-12-03 12:26 UTC, janden commented on setup.py
> +    author="Joakim Anden, Vineet Bansal, Robbie Brook, Itay Sason, Yoel Shkolnisky, Garrett Wright, Junchao Xia",
Add Ayelet Heimowitz.

2020-12-03 12:29 UTC, garrettwrong commented on setup.py
> +    author="Joakim Anden, Vineet Bansal, Robbie Brook, Itay Sason, Yoel Shkolnisky, Garrett Wright, Junchao Xia",
Sure, added.

2020-12-03 12:31 UTC, janden approved these changes

2020-12-04 11:29 UTC, merged