ArrayImageSource admit numpy
ComputationalCryoEM/ASPIRE-Python pull request #449
Opened 2021-08-31 16:49 UTC by j-c-c

Adds code and tests for using numpy arrays directly with ArrayImageSource.

2021-09-01 13:57 UTC, garrettwrong commented
Cool so I think in `tests/test_array_image_source.py`, we need to add a test that exercises the new branch. It's a sort of silly test, but we mainly want to ensure we didn't typo etc in a way that would make us crash.  IE, its just a smoke test.  Copied from `testArrayImageSource`.

```
    def testArrayImageSourceFromNumpy(self):
        """                                                                              
        An Array can be wrapped in an ArrayImageSource when we need to deal with ImageSource objects.                                                                            
                                                                                         
        This checks round trip conversion does not crash and returns identity.
        """

        # Create an ArrayImageSource directly from Numpy array
        src = ArrayImageSource(self.ims_np)

        # Ask the Source for all images in the stack as a Numpy array
        ims_np = src.images(start=0, num=np.inf).asnumpy()  

        # Comparison should be yield identity
        self.assertTrue(np.allclose(im, self.ims_np))
```

I have not tested this, but I think something like this should work fine for us.  @j-c-c , could you try to add this into the branch, test it, commit, and push it up?

2021-09-02 11:37 UTC, garrettwrong commented on src/aspire/source/image.py
> +        :param im: An `Image` or Numpy array object representing image data served up by this `ImageSource`
maybe missing punctuation (, or .) at end of line.

2021-09-02 11:41 UTC, garrettwrong requested changes
Looks good so far, thanks.  We still need to:

1. Add a test that tries to create a class with non compliant input (say a numpy array with shape (3,2,1) ), and check it returns a meaningful error message. 
 
2. Use this feature to simplify some of the tutorial/example code.

2021-09-03 16:55 UTC, garrettwrong approved these changes
Cool, I think this covers the issue.  Thanks.

2021-09-09 13:58 UTC, janden approved these changes
LGTM

2021-09-09 15:59 UTC, merged