Proposed README changeset
ComputationalCryoEM/ASPIRE-Python pull request #451
Opened 2021-09-01 18:32 UTC by garrettwrong

Minor README changes.  Has some typos for reviewers to catch.

Closes #450 .

2021-09-01 18:36 UTC, chris-langfield requested changes
grammar

2021-09-01 18:36 UTC, chris-langfield commented on README.md
> +# and additional installs the developer tools extras:
and additionally installs

2021-09-01 18:37 UTC, j-c-c commented on README.md
> +You may optionally install additional packages for GPU extension:
I think you meant "extensions"

2021-09-01 18:38 UTC, j-c-c requested changes
Looks good other than typo

2021-09-01 18:43 UTC, garrettwrong commented on README.md
> +# and additional installs the developer tools extras:
yup, fixed.

2021-09-01 18:43 UTC, garrettwrong commented on README.md
> +You may optionally install additional packages for GPU extension:
indeed, thanks

2021-09-01 18:49 UTC, chris-langfield approved these changes
nice!

2021-09-01 18:53 UTC, j-c-c approved these changes

2021-09-02 12:08 UTC, janden approved these changes

2021-09-02 12:08 UTC, merged