Empiar 475
ComputationalCryoEM/ASPIRE-Python pull request #478
Opened 2021-10-08 18:05 UTC by chris-langfield

Corrects an issue (see #475) where if an `.mrcs` file only contains one particle in the stack, it will be loaded as a 2D numpy array, rather than 3D, which the code in `relion._images` expects.

2021-10-08 18:53 UTC, garrettwrong commented on tests/saved_test_data/sample_relion_data.star
> +  916.590156  3057.649585            1     0.601333  -120.014857 000001@sample_one_particle.mrcs micrograph.mrc   300.000000 21186.804688 21363.109375	   7.476096     2.700000     0.000000     1.0000
Do you need to add the `sample_one_particle.mrcs` file or am I misunderstanding?

2021-10-08 19:55 UTC, chris-langfield commented on tests/saved_test_data/sample_relion_data.star
> +  916.590156  3057.649585            1     0.601333  -120.014857 000001@sample_one_particle.mrcs micrograph.mrc   300.000000 21186.804688 21363.109375	   7.476096     2.700000     0.000000     1.0000
yes, but i decided against modiying 'sample_relion_data.star' itself because other scripts use it. Instead I made a new STAR file

2021-10-11 15:23 UTC, garrettwrong requested changes
Looks like we patched the bug, thanks! I think the unit test extension might justify being refactored/cleaned up a little since we are in here.

2021-10-11 15:23 UTC, garrettwrong commented on tests/saved_test_data/sample_relion_data.star
> -  916.590156  3057.649585            1     0.601333  -120.014857 000017@sample.mrcs micrograph.mrc   300.000000 21186.804688 21363.109375     7.476096     2.700000     0.000000     1.000000     0.000
If the only difference between these files is a newline at EOF we should just leave the original.

Unless a dataformat (starfile in this case) says something specific about it, a trailing new line is good practice.

2021-10-11 15:23 UTC, garrettwrong commented on tests/test_starfile_stack.py
> +        ) as path, importlib_resources.path(
can we parameterize this test, (or alternatively make two subclasses of a generic class) and just run two cases, once for each input file? 

I feel like writing both tests together complicates the code, and wouldn't really give distinct feedback as a unit test (which case broke it?).

2021-10-11 15:23 UTC, garrettwrong commented on tests/test_starfile_stack.py
>              temp_file_path = os.path.join(temp_folder_path, "sample.mrcs")
I know its not a line that you touched but while we are in here we might be able to improve the tempfolder path.  Should be able to find better examples (using builtin functions/contexts) elsewhere in the unit tests.

2021-10-12 14:20 UTC, garrettwrong approved these changes

2021-10-12 14:22 UTC, garrettwrong commented
Resolved comments as they now relate to the refactoring issue. Bugfix looks good, we should move it soon. Thanks.

2021-10-14 12:55 UTC, janden approved these changes
Good catch!

2021-10-14 13:08 UTC, merged