Volume Projection Tutorial
ComputationalCryoEM/ASPIRE-Python pull request #497
Opened 2021-10-27 13:51 UTC by garrettwrong

Researcher requested an example of using ASPIRE tools to generate volume projects using prescribed rotations.

This is a draft for internal review/discussion.  There are similarities between this and some blocks of other tutorials.

2021-10-28 19:13 UTC, j-c-c requested changes
Looks great. Just a small typo and one comment for you.

2021-10-28 19:13 UTC, j-c-c commented on gallery/tutorials/generating_volume_projections.py
> +# a starting indexand number of images.
Missing a space "index and"

2021-10-28 19:13 UTC, j-c-c commented on gallery/tutorials/generating_volume_projections.py
> +src.projections(0, 3).show()
Not sure if this is of much concern, but these images appear a bit small and create a small thumbnail image. If it's something we care about it looks like we can change `figsize=(width,height)`

2021-10-28 19:26 UTC, garrettwrong commented on gallery/tutorials/generating_volume_projections.py
> +src.projections(0, 3).show()
Yeah, that's a good Idea. I forgot all about that option 😅 .

2021-10-29 12:06 UTC, garrettwrong commented on gallery/tutorials/generating_volume_projections.py
> +src.projections(0, 3).show()
Turns out the figsize is clamped by the gallery, but I put a different tweak.  Default was 5 columns, but I changed to min(5, n_images)... so in this case 3 columns.  Image are slightly bigger, and centered, now.

2021-10-29 13:41 UTC, j-c-c commented on gallery/tutorials/generating_volume_projections.py
> +src.projections(0, 3).show()
Nice. Yeah, I was wondering about the choice of 5 columns. Looks good.

2021-10-29 13:41 UTC, j-c-c approved these changes

2021-10-29 14:06 UTC, garrettwrong commented
Cool, thanks.  Since this primarily just adds a tutorial doc I think we can relieve Joakim from reviewing this one too.  We can always give it another go.

2021-10-29 14:08 UTC, merged