Docstring for `ImageSource.eval_filters()`
ComputationalCryoEM/ASPIRE-Python pull request #526
Opened 2021-12-03 21:49 UTC by chris-langfield

Closes #43 

This method applies the `unique_filters` of an `ImageSource` object to an `Image` passed in via `Image.filter()`. It is used in both `ImageSource.vol_forward()` and `ImageSource.im_backward()`. I don't believe it is unnecessary, but I could see some confusion arising from its placement next to `eval_filter_grid` (#38 #517), which does something a bit different and maybe doesn't belong. 

To close out this issue I propose to add a docstring for clarity, as I don't see a need to alter or remove the method.

2021-12-06 21:06 UTC, chris-langfield commented
As discussed earlier today, this method is probably good to stay. Only change is that I added a docstring to emphasize that the method applies the filters to actual image data, rather than just computing filter kernels on a grid. @garrettwrong

2021-12-07 15:15 UTC, garrettwrong requested changes
Small change. Then feel free to undraft.

Thanks for looking into this and documenting in the issue. Makes more sense to me now.

2021-12-07 15:15 UTC, garrettwrong commented on src/aspire/source/image.py
> +        :return: A 3D `Image` with the unique filters of the source applied at the given indices.
Instead of "A 3D `Image`..." , maybe just say "`Image` instance...".

2021-12-07 15:30 UTC, chris-langfield commented
Change was made thanks!

2021-12-07 15:37 UTC, garrettwrong submitted a review, later dismissed

2021-12-08 10:50 UTC, janden requested changes

2021-12-08 10:50 UTC, janden commented on src/aspire/source/image.py
>      def eval_filters(self, im_orig, start=0, num=np.inf, indices=None):
As discussed in #43, would make more sense to call this `_apply_filters`.

2021-12-08 15:08 UTC, janden commented on src/aspire/source/image.py
>      def eval_filters(self, im_orig, start=0, num=np.inf, indices=None):
Thanks!

2021-12-08 15:09 UTC, janden approved these changes

2021-12-08 15:36 UTC, merged