Avoid deprecation warnings in `importlib_resources`
ComputationalCryoEM/ASPIRE-Python pull request #529
Opened 2021-12-13 17:00 UTC by chris-langfield

Closes #503 

We have copied the methods that we still use from the legacy API of `importlib_resources` into a file in `aspire/utils`. This way, we can avoid the deprecation warnings.

We do this with the knowledge that `importlib_resources` will be replaced wholesale with `importlib.resources` once we drop support for Python 3.6. This is because `importlib.resources` was introduced in 3.7. Once that is done, this file will be deleted. 

The relevant methods are from https://github.com/python/importlib_resources/blob/main/importlib_resources/_legacy.py

2021-12-13 20:25 UTC, garrettwrong requested changes
Add a little to the doc, otherwise if the warnings went away this should be good. Thanks!

2021-12-13 20:25 UTC, garrettwrong commented on src/aspire/utils/importlib_legacy.py
> +# rewritten with importlib.resources. This file will then be deleted.
This is good, but add a few hyperlinks including where we copied the patches from.  Thanks.

2021-12-14 14:02 UTC, garrettwrong commented
Hey, if you merge and/or rebase this with the latest develop the CI should resolve.

2021-12-14 16:04 UTC, garrettwrong commented on src/aspire/utils/importlib_legacy.py
> +# rewritten with importlib.resources. This file will then be deleted.
Perfect thanks!

2021-12-14 16:07 UTC, garrettwrong approved these changes
Cool. I see the warning are gone in the earlier commit. Should be good enough to hold us over until 3.6 goes away. Thanks

2021-12-17 14:21 UTC, janden approved these changes

2021-12-17 15:08 UTC, merged