Update authors for this release
ComputationalCryoEM/ASPIRE-Python pull request #571
Opened 2022-02-15 20:08 UTC by garrettwrong

2022-02-15 20:35 UTC, garrettwrong commented
I think this CI broke due to a recent FINUFFT release.  I'm not sure whether it is our tests which are bad, or if the release has a problem yet.

2022-02-16 08:39 UTC, janden requested changes

2022-02-16 08:39 UTC, janden commented on CONTRIBUTORS.rst
> +   | Ayelet Heimowitz | ayeltg          | ayeleth@ariel.ac.il       | Tel Aviv University               |
Ariel University

2022-02-16 12:37 UTC, garrettwrong commented on CONTRIBUTORS.rst
> +   | Ayelet Heimowitz | ayeltg          | ayeleth@ariel.ac.il       | Tel Aviv University               |
Oof, my mistake. Updated. Thank you.

2022-02-16 12:38 UTC, janden approved these changes

2022-02-16 15:33 UTC, garrettwrong commented
Going to admin push this in just to get it out of the way. Low risk change.

2022-02-16 15:33 UTC, merged