New downsample method
ComputationalCryoEM/ASPIRE-Python pull request #606
Opened 2022-04-05 16:04 UTC by chris-langfield

2022-04-25 17:39 UTC, chris-langfield commented
Using `centered_fft2` fixes the issues from #608. The new downsampling method now passes the logical tests introduced in #567 

It is worth noting that `Volume.downsample()` is not currently replaced with this new method. 
It uses the related but not identical method `aspire.image.downsample()`. 

Although this method uses a similar strategy, I believe there is a conversation to be had about how to best go about vetting and possibly improving this 3D downsampling method.  (I made an issue: #617)

2022-04-25 18:14 UTC, j-c-c requested changes
Looks good! Couple small things.

2022-04-25 18:14 UTC, j-c-c commented on src/aspire/image/image.py
> +        fx = np.array([fft.centered_fft2(self.data[i]) for i in range(self.n_images)])
Should be able to just do `fx = fft.centered_fft2(self.data)`. I don't think the loop is necessary. Same below for `ifft`.

2022-04-25 18:14 UTC, j-c-c commented on src/aspire/image/image.py
> +        ) * (ds_res**2 / self.res**2)
Maybe just `out = np.real(fft.centered_ifft2(crop_fx)) * (ds_res**2 / self.res**2)`?

2022-04-25 18:15 UTC, j-c-c requested changes
Looks good! Couple small things.

2022-04-25 19:09 UTC, chris-langfield commented on src/aspire/image/image.py
> +        ) * (ds_res**2 / self.res**2)
I prefer the current set up (the `return Image(out)` echoes the pattern used in other parts of the code)

2022-04-26 13:22 UTC, j-c-c commented on src/aspire/image/image.py
> +        ) * (ds_res**2 / self.res**2)
This was just in reference to the unnecessary list comprehension. Agree with matching other parts of the code for returning an `Image`.

2022-04-26 13:23 UTC, j-c-c approved these changes
Looks good!

2022-04-26 13:31 UTC, chris-langfield commented on src/aspire/image/image.py
> +        ) * (ds_res**2 / self.res**2)
Oh totally misunderstood. Your comment is absolutely right and I made the change thanks!

2022-04-28 07:43 UTC, janden approved these changes
Looks good.

2022-04-28 12:49 UTC, merged