`Filter.sign` method
ComputationalCryoEM/ASPIRE-Python pull request #656
Opened 2022-07-13 17:15 UTC by j-c-c

This PR creates a `Filter.sign` method that returns `LambdaFilter(self, np.sign)`, ie. a filter object which can later be evaluated to determine the signs of the evaluation over the underlying filter (mentioned in issue #308).

Additionally, a test for the method was added and the use of the `LambdaFilter` for this purpose in `phase_flip()` was replaced: https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/source/image.py#L374-L385

2022-07-13 17:30 UTC, garrettwrong requested changes
Looks good, thanks for tackling the issue.  One small request, otherwise lgtm.

2022-07-13 17:30 UTC, garrettwrong commented on src/aspire/operators/filters.py
> +    def sign(self):
I know other methods are missing docs, but lets add a docstring here. One sentence is fine.

2022-07-13 20:11 UTC, garrettwrong approved these changes
Cool, I'd merge this in, but in this case we should probably wait to make sure I wasn't confused about Joakim's intent. Thanks!

2022-07-14 12:55 UTC, j-c-c commented
@garrettwrong sounds good. I'll undraft and wait for Joakim to take a look. Thanks for the review!

2022-07-21 12:44 UTC, janden approved these changes
Looks good. Thanks!

2022-07-21 14:12 UTC, merged