Use multiprocessing for Class Averaging alignment
ComputationalCryoEM/ASPIRE-Python pull request #660
Opened 2022-07-26 19:31 UTC by garrettwrong

Implements a `ray` based multiprocessing pool for the ReddyChatterji class average alignment methods for some tasty speedups.

Has some logic that disables mp runs for development environments that are xfail, runs serially. This is actually nice since it will cover bought areas of code.

Adds some utils for suggesting number of cores based on mem usage/avail, phys cpu, and virtual cpu.

Moves Reddy Chatterji registration algo into it's own file.

Still WIP.

2022-07-27 11:17 UTC, garrettwrong commented
Looks like there is a moderate conflict/regression with #643 , but I should be able to resolve.

After that I will want to manually run a few verifications again and can pass PR to another dev for initial review.

2022-08-04 15:01 UTC, janden requested changes
Looks good. The multiprocessing code looks cleaner than I expected, although I suspect it took quite a bit of work to get there… Just a few comments and questions.

2022-08-04 15:01 UTC, janden commented on src/aspire/classification/__init__.py
> +from .reddy_chatterji import reddy_chatterji_register
Since this is internal I don't think it needs to be accessed from the second level (below we seem to import it from the third level anyhow).

2022-08-04 15:01 UTC, janden commented on src/aspire/utils/multiprocessing.py
> +        "mememory": mem_based_cpu_suggestion(),
`memory`

2022-08-04 15:01 UTC, janden commented on src/aspire/utils/multiprocessing.py
> +    logger.info(f"Suggesting {n} multi processor based on {k}.")
`multi processor` → `processes`

2022-08-04 15:01 UTC, janden commented on src/aspire/classification/averager2d.py
> +            logger.debug(
Potentially spammy?

2022-08-04 15:01 UTC, janden commented on src/aspire/classification/averager2d.py
> +    def __init__(self, composite_basis, src, num_procs=1, dtype=None):
Elsewhere we default to `"auto"` (e.g. `ReddyChatterjiAverager2D`). Why one instead here?

2022-08-04 15:01 UTC, janden commented on src/aspire/classification/averager2d.py
> +        if num_procs == "auto":
Out of curiousity, why `"auto"` instead of `None` or `-1`?

2022-08-04 15:01 UTC, janden commented on src/aspire/utils/multiprocessing.py
> +def get_num_multi_procs():
To line up with the others, maybe just `cpu_suggestion` or `num_procs_suggestion`?

2022-08-04 18:22 UTC, garrettwrong commented on src/aspire/utils/multiprocessing.py
> +def get_num_multi_procs():
Sure.

2022-08-04 18:22 UTC, garrettwrong commented on src/aspire/classification/averager2d.py
> +        if num_procs == "auto":
No reason. `None` works for me, I'll change.

2022-08-04 18:22 UTC, garrettwrong commented on src/aspire/classification/averager2d.py
> +    def __init__(self, composite_basis, src, num_procs=1, dtype=None):
I did this because only the RC classes are "auto".  I haven't implemented multiprocessing for the alignment methods of the brute force methods here.  I can, but they're not as important.  At that point, yes I would agree it should be "auto" throughout (well `None`  :) ).  I can change here, but then would need to change the other two classes to be 1.  If you prefer that lmk.

2022-08-04 18:22 UTC, garrettwrong commented on src/aspire/classification/averager2d.py
> +            logger.debug(
sure, can always add it back for debugging.

2022-08-04 18:22 UTC, garrettwrong commented on src/aspire/utils/multiprocessing.py
> +    logger.info(f"Suggesting {n} multi processor based on {k}.")
done

2022-08-04 18:22 UTC, garrettwrong commented on src/aspire/utils/multiprocessing.py
> +        "mememory": mem_based_cpu_suggestion(),
😊 fixed, thanks. I must have looked at that a twenty times and still missed it.

2022-08-04 18:23 UTC, garrettwrong commented on src/aspire/classification/__init__.py
> +from .reddy_chatterji import reddy_chatterji_register
Yeah, I wasn't sure what to do with this myself.  I did refactor it so it could be called independently.  Importing from third level was a mistake, but keeping it internal might make more sense anyway.  I'll change.

2022-08-04 18:40 UTC, garrettwrong commented
Note for myself to remember to squash this PR on merge.  Too many dev commits ...

2022-08-05 08:55 UTC, janden commented on src/aspire/classification/averager2d.py
> +        if num_procs == "auto":
Ok cool. Thanks!

2022-08-05 08:56 UTC, janden commented on src/aspire/classification/averager2d.py
> +    def __init__(self, composite_basis, src, num_procs=1, dtype=None):
No just leave it at one. Maybe make a note or an issue to remind ourselves.

2022-08-05 08:56 UTC, janden commented on src/aspire/classification/__init__.py
> +from .reddy_chatterji import reddy_chatterji_register
Yeah I think so.

2022-08-05 08:57 UTC, janden submitted a review, later dismissed

2022-08-05 08:57 UTC, janden commented
Ok this is basically done. Just that one CR that may need an issue or a TODO note in the code.

2022-08-05 12:26 UTC, garrettwrong commented on src/aspire/classification/averager2d.py
> +    def __init__(self, composite_basis, src, num_procs=1, dtype=None):
https://github.com/ComputationalCryoEM/ASPIRE-Python/issues/677

2022-08-08 16:15 UTC, garrettwrong commented
@janden , ran a really large (100k..) experiment and found a reason to add a small patch.  Probably should take a look at the new change.  If it looks okay, will merge.  Thanks!

2022-08-11 12:31 UTC, janden approved these changes

2022-08-11 12:33 UTC, merged