Return info dictionary from `ImageSource.save()`
ComputationalCryoEM/ASPIRE-Python pull request #719
Opened 2022-10-17 19:25 UTC by chris-langfield

Closes #545 by returning information about the files saved.

2022-10-18 15:22 UTC, j-c-c commented on src/aspire/source/image.py
> +        return info
Maybe add the `return` to the docs.

2022-10-18 15:25 UTC, j-c-c reviewed
One comment. Otherwise, LGTM.

2022-10-18 15:40 UTC, chris-langfield commented on src/aspire/source/image.py
> +        return info
done thanks

2022-10-19 17:59 UTC, j-c-c submitted a review, later dismissed

2022-10-19 18:24 UTC, garrettwrong requested changes
One doc string change otherwise lgtm, thanks!

2022-10-19 18:24 UTC, garrettwrong commented on src/aspire/source/image.py
> +        list of the saved particle stack .mrcs filenames.
Hey, I didn't realize this was happening before Josh pointed it out to me, but I think the line beginning with `list` needs to be indented for Sphinx to parse it.

2022-10-20 11:45 UTC, garrettwrong commented on src/aspire/source/image.py
> +        list of the saved particle stack .mrcs filenames.
Cool, had it checked out and rebuilt the doc, lgtm. Thanks!

2022-10-20 11:46 UTC, garrettwrong approved these changes

2022-11-02 15:53 UTC, merged