Daily docs build
ComputationalCryoEM/ASPIRE-Python pull request #800
Opened 2022-12-08 19:45 UTC by j-c-c

Adds a github actions workflow that checks out `develop` and builds the docs including the gallery. This runs on a daily schedule at 12am UTC (7pm EST). 

Scheduled workflows will only run from the default (`master`) branch, so to test scheduling I forked the repo and merged the `daily_workflow.yml` into `master` in the fork to confirm that the scheduler does trigger the workflow. I also confirmed that the workflow does indeed build the docs by triggering the workflow on  a `push` here inside this branch. Everything appears to be functioning properly.

This closes #707

2022-12-12 12:19 UTC, garrettwrong requested changes
Can you save the docs as an artifact? Maybe retain artifact for a week, that way they would be reviewed if needed. Otherwise lgtm, thanks!

2022-12-12 13:50 UTC, j-c-c commented
> Can you save the docs as an artifact? Maybe retain artifact for a week, that way they would be reviewed if needed. Otherwise lgtm, thanks!

Good idea. I'll test it out on the fork and report back. Thanks!

2022-12-13 04:32 UTC, j-c-c commented
@garrettwrong, the workflow now saves the docs as an artifact and retains for 7 days. Each docs artifact is about 27.5MB. Holding each for 7 days will put us at a running total of about 200MB of storage use. From what I'm seeing [here](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions) it looks like we're given 500MB of github actions storage. 

If you think this could be a problem we could reduce retention days or run the workflow less than daily. Let me know what you think.

2022-12-13 12:46 UTC, garrettwrong commented
While they don't spell it out, I read
```
GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners. 
```
to say that we don't need to worry about the usage limits.  I can tell you we blow through those monthly minute caps most days... (think about it...)

Good call looking into it though.

2022-12-13 12:49 UTC, garrettwrong approved these changes
Code looks nice, thanks.

This either needs to be rebased (squashed) into a single commit, or we need to do the squash merge. The merge should be one commit for this now that the testing is complete. Thanks.

2022-12-13 16:06 UTC, j-c-c commented
> Code looks nice, thanks.
> 
> This either needs to be rebased (squashed) into a single commit, or we need to do the squash merge. The merge should be one commit for this now that the testing is complete. Thanks.

Thanks. Will do the squash merge when we're ready to merge.

2022-12-16 15:47 UTC, garrettwrong commented
Discussed team meeting, ready to merge to develop.

2022-12-16 15:48 UTC, merged