Normalize background dtype bug
ComputationalCryoEM/ASPIRE-Python pull request #813
Opened 2022-12-15 17:09 UTC by chris-langfield

#812

2022-12-15 18:15 UTC, chris-langfield commented
Looks like this change introduced a bug for Python 3.8 on only Windows and Ubuntu. (The tox Python 3.8 stable environment passes on `decaf`, which is Springdale -> RedHat). Looking into it

2022-12-15 19:57 UTC, chris-langfield commented
Fixed by using `utest_tolerance` for the dtype. Will look at testing preprocessing for different dtypes as part of this PR

2022-12-16 17:26 UTC, garrettwrong requested changes
Might as well parametrize over even and odds 😇 now that you've gone this far. See if its quick and I'll reapprove.

2022-12-16 17:45 UTC, chris-langfield commented
`Whiten` has separate tests for even and odd so I just parametrize over the dtypes. Added a note to the even test (odd already has one)

2022-12-16 17:47 UTC, garrettwrong approved these changes
Awesome, thanks!

2022-12-16 18:18 UTC, j-c-c approved these changes
Looks great!

2022-12-16 18:19 UTC, merged