Drop `parameterized_class` from tests
ComputationalCryoEM/ASPIRE-Python pull request #815
Opened 2022-12-20 19:28 UTC by chris-langfield

WIP to close #803 

In adding parametrization over dtype, I have found an issue with `Image` shifting for `np.float32`.

2022-12-22 18:57 UTC, chris-langfield commented
It turned out that passing the real image data as `float32` into the FFT returns a different value from passing it in as `float64`, which caused numerical instability in the rest of the shifting algorithm. This PR patches the `_im_translate` method by upcasting the real data before the shifting algorithm, and then casting back to the original dtype before return.

2023-01-03 17:13 UTC, garrettwrong requested changes
I took a look at the issue visually and numerically. The relative error seemed okay to me, so I am suggesting normalizing the image data before the test instead of bumping the `atol` or casting.  That appears to work well.  

The input data here is [0,250].  Another thing that I can think of is that we might have a normalization bug somewhere in the algo.

This makes me wonder why we don't just use roll for integer shifts 😇  and reserve this for subpixel or shifts already in Fourier space. I'll make an issue for that.

2023-01-03 17:13 UTC, garrettwrong commented on tests/test_image.py
> +    im_np = misc.face(gray=True).astype(dtype)
redundant, delete

2023-01-03 17:13 UTC, garrettwrong commented on tests/test_image.py
> +    im_np = misc.face(gray=True).astype(dtype)[np.newaxis, :size, :size]
lets normalize these values to 0 1
```
def get_images(parity=0, dtype=np.float32):
    size = 768 - parity
    # numpy array for top-level functions that directly expect it                                                                
    im_np = misc.face(gray=True).astype(dtype)[np.newaxis, :size, :size]
    denom = np.max(np.abs(im_np))
    im_np = im_np / denom  # Normalize test image data to 0,1                                                                    
    # Independent Image object for testing Image methods                                                                         
    im = Image(im_np.copy())
    return im_np, im
```

2023-01-03 17:13 UTC, garrettwrong commented on src/aspire/image/image.py
> +        im = self.stack_reshape(-1)._data.astype(np.float64)
see my other remarks. This file can be reverted to `origin/develop` if you take that other patch.

2023-01-03 17:13 UTC, garrettwrong commented on tests/test_image.py
> +    # don't need to parametrize this test
I think we can rm the `# don't need to parametrize this test`, or at least, put it under the docstring.

2023-01-03 17:20 UTC, garrettwrong commented
Created #822

2023-01-03 17:27 UTC, chris-langfield commented on tests/test_image.py
> +    im_np = misc.face(gray=True).astype(dtype)
done thanks

2023-01-03 17:27 UTC, chris-langfield commented on tests/test_image.py
> +    im_np = misc.face(gray=True).astype(dtype)[np.newaxis, :size, :size]
cool, thank you for looking into this!

2023-01-03 21:03 UTC, garrettwrong submitted a review, later dismissed
Cool, thanks for making the changes. Let's get one more pair of eyes on it (Josh) before merging.

2023-01-04 20:35 UTC, j-c-c reviewed
Looks good! Couple small things.

2023-01-04 20:35 UTC, j-c-c commented on tests/test_image.py
> +    im_np = im_np / denom  # Normalize test image data to 0,1
`im_np = im_np / denom ` --> `im_np /= denom`

2023-01-04 20:35 UTC, j-c-c commented on tests/test_image.py
> +    mdim_ims = Image(mdim_ims_np)
Maybe add same comment as above: "# Independent multi-dimensional Image stack object for testing Image methods"

2023-01-04 20:35 UTC, j-c-c commented on tests/test_image.py
> +@pytest.mark.parametrize("parity,dtype", params)
No space after the comma in `"parity,dtype"` really bugs me, but I see that's the convention in pytest docs.

2023-01-05 16:46 UTC, j-c-c approved these changes

2023-01-23 12:40 UTC, merged