Changed Angstrom unit to angstrom
ComputationalCryoEM/ASPIRE-Python pull request #963
Opened 2023-06-20 15:09 UTC by krissowat

first PR !!

2023-06-20 15:15 UTC, garrettwrong requested changes
just one line

2023-06-20 15:15 UTC, garrettwrong commented on tests/saved_test_data/sample_data_model.star
> +_rlnangstromResolution #3
I think we need to commit this change.

2023-06-20 15:18 UTC, krissowat commented on tests/saved_test_data/sample_data_model.star
> +_rlnangstromResolution #3
Fixed.

2023-06-20 15:20 UTC, garrettwrong approved these changes, later dismissed

2023-06-20 16:04 UTC, janden requested changes
Looks great! Just a few things.

2023-06-20 16:04 UTC, janden commented on gallery/tutorials/data/ctffind4/diagnostic_output.txt
> +# Pixel size: 1.000 angstroms ; acceleration voltage: 200.0 keV ; spherical aberration: 2.26 mm ; amplitude contrast: 0.07
This is the actual output of the CTFFIND4 tool, so it should probably stay the same. (Same below for `input.txt`.)

2023-06-20 16:04 UTC, janden commented on gallery/tutorials/tutorials/ctf.py
> +    defocus=10000,  # angstrom, 10000A = 1um
Spaces between value and units (so `10000 A = 1 um`).

2023-06-21 14:22 UTC, janden commented on gallery/tutorials/tutorials/ctf.py
> +    defocus=10000,  # angstrom, 10000A = 1um
Great. There's a second instance of this (just below). Can you fix that one as well?

2023-06-21 14:23 UTC, janden commented on gallery/tutorials/data/ctffind4/diagnostic_output.txt
> +# Pixel size: 1.000 angstroms ; acceleration voltage: 200.0 keV ; spherical aberration: 2.26 mm ; amplitude contrast: 0.07
Thanks. This also needs to be changed for `input.txt`.

2023-06-21 14:37 UTC, garrettwrong approved these changes
Great, thanks!

2023-06-21 14:55 UTC, janden approved these changes
LGTM

2023-06-21 15:08 UTC, garrettwrong commented
We're going to disregard the CI jobs failing due to APPLE for the time being. Ready to merge.

2023-06-21 15:09 UTC, merged