split out and mrc and tiff file reading for apple.picker
ComputationalCryoEM/ASPIRE-Python pull request #972
Opened 2023-07-03 18:07 UTC by garrettwrong

Still need to add tests etc.

2023-07-05 14:09 UTC, garrettwrong commented
Thinking I should probably just implement this as part of `Image.load` and try to use `Image` in `apple`.

2023-07-05 17:26 UTC, garrettwrong commented
Closes #971 #786 

786's `testFileCorruption` is now handled by a much smaller and direct test of `Image`.  This was the worst offender.

2023-07-25 11:41 UTC, garrettwrong commented
Restarting one of these tests to see if it shares the MRC warning issue found in `develop`.

2023-07-25 15:44 UTC, j-c-c requested changes
Looks good! Just a couple small things.

2023-07-25 15:44 UTC, j-c-c commented on src/aspire/image/image.py
> +        :return: numpy array of image data.
Missing `param` here.

2023-07-25 15:44 UTC, j-c-c commented on src/aspire/image/image.py
> +            raise RuntimeError(
Should we test this branch?

2023-07-25 15:44 UTC, j-c-c commented on tests/test_image.py
> +@pytest.mark.xfail(reason="Ray logging issue ray#37711", strict=False)
Nice find on that one!

2023-07-25 15:44 UTC, j-c-c commented on src/aspire/image/image.py
> +        # Attempt casting if user
Unfinished comment?

2023-07-25 15:51 UTC, garrettwrong commented on tests/test_image.py
> +@pytest.mark.xfail(reason="Ray logging issue ray#37711", strict=False)
grrrr

2023-07-25 15:51 UTC, garrettwrong commented on src/aspire/image/image.py
> +        # Attempt casting if user
yep, updated.

2023-07-25 15:51 UTC, garrettwrong commented on src/aspire/image/image.py
> +            raise RuntimeError(
Sure. Added.

2023-07-25 15:51 UTC, garrettwrong commented on src/aspire/image/image.py
> +        :return: numpy array of image data.
added, thanks

2023-07-25 15:59 UTC, j-c-c approved these changes
LGTM!

2023-07-25 15:59 UTC, garrettwrong commented
When the CI passes, I'm planning to merge this so we can get the patch for the broken CI test in ASAP.

2023-07-25 17:14 UTC, merged