More pytest conversions
ComputationalCryoEM/ASPIRE-Python pull request #991
Opened 2023-08-03 18:11 UTC by garrettwrong

Breaking off another partial piece of the swappable basis project #916 .  This PR converts multiple unit tests towards pytest so that they can later be tested against additional basis classes using fixtures.  Specifically the class_src and class2D tests pass upstream for all 2D basis.

This does not rewrite the hardcoded cov2d tests, but is a first step in doing so.

I believe this also removes the last usage of the parameterized package #803 (so a follow up pr/commit can be made to remove that package). 

This follows the `DiagMatrix` PR #987 , and will need to be reconciled once that is merged.

This is a rough draft, just stashing for now.

2023-09-11 19:18 UTC, j-c-c requested changes
Looks good! Just a few things.

2023-09-11 19:18 UTC, j-c-c commented on pyproject.toml
> -    "parameterized",
🎉

2023-09-11 19:18 UTC, j-c-c commented on src/aspire/basis/fle_2d.py
> +        # radial = self.get_radial()
Does this need to be removed?

2023-09-11 19:18 UTC, j-c-c commented on tests/test_covar2d.py
> +]
Any reason for not using "slow" FB for these tests as well? Just noticed it was added as expensive for the others.

edit: I'm seeing now that most of these tests are hardcoded. Guessing that's why.

2023-09-11 19:18 UTC, j-c-c commented on tests/test_covar2d.py
> +        h_ctf_fb = [basis.filter_to_basis_mat(f) for f in unique_filters]
Do we want to generalize `h_ctf_fb` to `h_ctf_basis`?

2023-09-11 19:18 UTC, j-c-c commented on tests/test_covar2d.py
> +    assert np.allclose(mean_coeff_ctf, result, atol=0.002)
Should we retain the tighter tolerance for `ctf_enabled`? It looks like this passed using our `utest_tolerance` before.

2023-09-11 19:18 UTC, j-c-c commented on tests/test_covar2d.py
> +    assert delta < 0.02
(Edit: My question here is probably out of scope for this PR since this is just a copied over test, but might be relevant in the future if we're going to move away from the hardcoded tests in this file.)

Is 0.02 a reasonable value here for an MSE? It looks like the signal values (or squared values) of `sim.projections` are smaller than this error. Not sure how well we expect the reconstruction to be. 

(2nd Edit: It looks like the reconstruction is inverted from the projections. Here's a look at the first projection and the first reconstruction image.)

`sim.projection[0]`:
<img width="756" alt="Screenshot 2023-09-11 at 3 09 54 PM" src="https://github.com/ComputationalCryoEM/ASPIRE-Python/assets/66811911/2ebbdfb6-ae04-4534-befa-bac2d59c5187">

`img_est[0]`:
<img width="790" alt="Screenshot 2023-09-11 at 3 11 33 PM" src="https://github.com/ComputationalCryoEM/ASPIRE-Python/assets/66811911/2570dd15-9f5a-4785-a581-e1af45a0dcfa">

2023-09-12 11:17 UTC, garrettwrong commented on src/aspire/basis/fle_2d.py
> +        # radial = self.get_radial()
vestigial, rm'd, thanks

2023-09-12 11:19 UTC, garrettwrong commented on tests/test_covar2d.py
> +]
Correct, cov2d tests are very much hard coded. I don't expect them to pass for other classes and rewriting cov2d tests top to bottom outside the initial scope.  I might get to that at the end of the project depending on the timeline.

2023-09-12 11:20 UTC, garrettwrong commented on tests/test_covar2d.py
> +        h_ctf_fb = [basis.filter_to_basis_mat(f) for f in unique_filters]
no. these tests only work for FFBBasis2D and will get deleted. Not worth the effort.

2023-09-12 12:01 UTC, j-c-c commented on tests/test_covar2d.py
> +]
Sounds good.

2023-09-12 12:03 UTC, j-c-c commented on tests/test_covar2d.py
> +        h_ctf_fb = [basis.filter_to_basis_mat(f) for f in unique_filters]
Ok sounds good.

2023-09-12 12:27 UTC, garrettwrong commented on tests/test_covar2d.py
> +    assert delta < 0.02
No, it isn't/won't-be relevant.

What you see is simply the CTF.

Changing to `clean_images` means we can _maybe_ change from `0.02` to `0.01` and have now introduced unqualified changes to test code that's been stable (albeit not good) for several years. Super. Hope its not flaky.

2023-09-12 12:33 UTC, garrettwrong commented on tests/test_covar2d.py
> +    assert np.allclose(mean_coeff_ctf, result, atol=0.002)
That is correct. There were two distinct tests, and they used different tolerances, but it doesn't really matter.... These tests won't help us where we are going...

Changed.

2023-09-12 19:19 UTC, j-c-c submitted a review, later dismissed
LGTM!

2023-09-12 21:03 UTC, janden requested changes
Cool! Just a few things to discuss here.

2023-09-12 21:03 UTC, janden commented on src/aspire/basis/fle_2d.py
> +    def filter_to_basis_mat(self, f):
This function doesn't seem to be tested anywhere. Should be possible to test the fidelity of the diagonal matrix representation by calling `evaluate`, filtering by the CTF, and calling `expand`, then comparing this with straight (diagonal) matrix multiplication with the output of this function.

2023-09-12 21:03 UTC, janden commented on tests/test_class2D.py
> +def sim_fixture2(volume, basis, img_size, dtype):
Brief comment on difference between this and `sim_fixture`?

2023-09-13 12:51 UTC, garrettwrong commented on tests/test_class2D.py
> +def sim_fixture2(volume, basis, img_size, dtype):
Added doc string for `sim_fixture` and `sim_fixture2`.

2023-09-13 12:57 UTC, garrettwrong commented on src/aspire/basis/fle_2d.py
> +    def filter_to_basis_mat(self, f):
That's true and partially a consequence of breaking up the project.  Test code that covered this (or some variant of it at this point was/) is upstream.

The coverage I did have was not a direct test though.  I'll try this out.

2023-09-13 14:49 UTC, garrettwrong commented on src/aspire/basis/fle_2d.py
> +    def filter_to_basis_mat(self, f):
I'm not sure this suggestion is working for FFB.  I'll bring it up later.

The function for FFB has not ever been unit tested outside of its use in cov2d (same as this was being tested upsteam).

2023-09-13 18:22 UTC, janden commented on src/aspire/basis/fle_2d.py
> +    def filter_to_basis_mat(self, f):
> I'm not sure this suggestion is working for FFB. I'll bring it up later.

Ok got it. We'll make an issue to revisit the accuracy of these functions then.

> The function for FFB has not ever been unit tested outside of its use in cov2d (same as this was being tested upsteam).

Makes sense.

2023-09-13 18:27 UTC, janden commented on src/aspire/basis/fle_2d.py
> +    def filter_to_basis_mat(self, f):
See #1016.

2023-09-13 18:32 UTC, janden approved these changes

2023-09-13 18:54 UTC, merged